### ISSUE TITLE
Alternative to ProjectTypeGuids is needed

### ISSUE THREAD

**Issue by itn3000** [JeffCyr/MSBuild.SolutionSdk#1]
Currently, sln has ProjectTypeGuids for informing project type to the IDE.

To aim alternative of sln, I think SolutionSdk should support the similar feature.
sln's ProjectTypeGuids spec is following;

* value is GUID
    * should it be changed the format?
* expressing project type
    * like C#, C++, or another
* project may have multiple value
    * for expressing like "PCL"+"C#" project
* currently, it must exist if using Visual Studio
    * should it be autodetected by default in SolutionSdk?

**Comment by JeffCyr** [comment]
I was planning to infer project type based on the project file extension when generating .sln files. I don't think it's necessary to include all the actual project types of the project file. Do you think it is for a particular scenario?

Visual Studio already scan the project files to load the appropriate project system. I think that VS could eventually work fine without project types at all in the solution file.
https://github.com/dotnet/project-system/blob/master/docs/opening-with-new-project-system.md

**Comment by itn3000** [comment]
I had not been seen the page, thank you for pointing.

I thought the third party project type like 'wixproj',
so ProjectTypeGuid setting is needed for interoperability of current SLN.

But ProjectTypeGuid is currently needed only for interoperability, so I begin to think determining ProjectTypeGuid is solution generator's business.

Now I got the idea that ProjectTypeGuid is not needed in SolutionSDK, please close this issue.
